 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/trustees/users", type: :request do
  # Trustees::User. As you add validations to Trustees::User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Trustees::User.create! valid_attributes
      get trustees_users_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user = Trustees::User.create! valid_attributes
      get trustees_user_url(trustees_user)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_trustees_user_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      user = Trustees::User.create! valid_attributes
      get edit_trustees_user_url(trustees_user)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Trustees::User" do
        expect {
          post trustees_users_url, params: { trustees_user: valid_attributes }
        }.to change(Trustees::User, :count).by(1)
      end

      it "redirects to the created trustees_user" do
        post trustees_users_url, params: { trustees_user: valid_attributes }
        expect(response).to redirect_to(trustees_user_url(@trustees_user))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Trustees::User" do
        expect {
          post trustees_users_url, params: { trustees_user: invalid_attributes }
        }.to change(Trustees::User, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post trustees_users_url, params: { trustees_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested trustees_user" do
        user = Trustees::User.create! valid_attributes
        patch trustees_user_url(trustees_user), params: { trustees_user: new_attributes }
        user.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the trustees_user" do
        user = Trustees::User.create! valid_attributes
        patch trustees_user_url(trustees_user), params: { trustees_user: new_attributes }
        user.reload
        expect(response).to redirect_to(trustees_user_url(user))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        user = Trustees::User.create! valid_attributes
        patch trustees_user_url(trustees_user), params: { trustees_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested trustees_user" do
      user = Trustees::User.create! valid_attributes
      expect {
        delete trustees_user_url(trustees_user)
      }.to change(Trustees::User, :count).by(-1)
    end

    it "redirects to the trustees_users list" do
      user = Trustees::User.create! valid_attributes
      delete trustees_user_url(trustees_user)
      expect(response).to redirect_to(trustees_users_url)
    end
  end
end
