 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/managers/users", type: :request do
  # Managers::User. As you add validations to Managers::User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Managers::User.create! valid_attributes
      get managers_users_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      user = Managers::User.create! valid_attributes
      get managers_user_url(managers_user)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_managers_user_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      user = Managers::User.create! valid_attributes
      get edit_managers_user_url(managers_user)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Managers::User" do
        expect {
          post managers_users_url, params: { managers_user: valid_attributes }
        }.to change(Managers::User, :count).by(1)
      end

      it "redirects to the created managers_user" do
        post managers_users_url, params: { managers_user: valid_attributes }
        expect(response).to redirect_to(managers_user_url(@managers_user))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Managers::User" do
        expect {
          post managers_users_url, params: { managers_user: invalid_attributes }
        }.to change(Managers::User, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post managers_users_url, params: { managers_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested managers_user" do
        user = Managers::User.create! valid_attributes
        patch managers_user_url(managers_user), params: { managers_user: new_attributes }
        user.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the managers_user" do
        user = Managers::User.create! valid_attributes
        patch managers_user_url(managers_user), params: { managers_user: new_attributes }
        user.reload
        expect(response).to redirect_to(managers_user_url(user))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        user = Managers::User.create! valid_attributes
        patch managers_user_url(managers_user), params: { managers_user: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested managers_user" do
      user = Managers::User.create! valid_attributes
      expect {
        delete managers_user_url(managers_user)
      }.to change(Managers::User, :count).by(-1)
    end

    it "redirects to the managers_users list" do
      user = Managers::User.create! valid_attributes
      delete managers_user_url(managers_user)
      expect(response).to redirect_to(managers_users_url)
    end
  end
end
