 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/users/attendances", type: :request do

  # Attend. As you add validations to Attend, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # describe "GET /users/attendances/index" do
  #   it "renders a successful response" do
  #     Attendance.create! valid_attributes
  #     get attends_url
  #     expect(response).to be_successful
  #   end
  # end

  # describe "GET /users/attendances/show" do
  #   it "renders a successful response" do
  #     attend = Attendance.create! valid_attributes
  #     get users_attendance_url(attendance)
  #     expect(response).to be_successful
  #   end
  # end

  xdescribe "GET /users/attendances/new" do
    it "renders a successful response" do
      get new_users_attendance_url
      expect(response).to be_successful
    end
  end

  describe "GET /users/attendances/edit" do
    it "render a successful response" do
      attend = Attendance.create! valid_attributes
      get edit_users_attendance_url(attendance)
      expect(response).to be_successful
    end
  end

  describe "POST /users/attendances/create" do
    context "with valid parameters" do
      it "creates a new Attend" do
        expect {
          post users_attendances_url, params: { attend: valid_attributes }
        }.to change(Attendance, :count).by(1)
      end

      it "redirects to the created attend" do
        post users_attendances_url, params: { attend: valid_attributes }
        expect(response).to redirect_to(attendance_url(Attend.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Attend" do
        expect {
          post users_attendances_url, params: { attend: invalid_attributes }
        }.to change(Attendance, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post users_attendances_url, params: { attend: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /users/attendances/update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested attend" do
        attend = Attendance.create! valid_attributes
        patch attendance_url(attendance), params: { attend: new_attributes }
        attend.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the attend" do
        attend = Attendance.create! valid_attributes
        patch attendance_url(attendance), params: { attend: new_attributes }
        attend.reload
        expect(response).to redirect_to(attend_url(attendance))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        attend = Attendance.create! valid_attributes
        patch attendance_url(attendance), params: { attend: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /users/attendances/destroy" do
    it "destroys the requested attend" do
      attend = Attendance.create! valid_attributes
      expect {
        delete attendance_url(attendance)
      }.to change(Attendance, :count).by(-1)
    end

    it "redirects to the attends list" do
      attend = Attendance.create! valid_attributes
      delete attendance_url(attendance)
      expect(response).to redirect_to(attends_url)
    end
  end
end
